### ISSUE TITLE
HibernateDao.java中的空指针异常

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zhangwenling/springside#32]
```
What steps will reproduce the problem?
1.数据库中新建了一个表（自己建立的一个模块），里面没有
数据，执行列表页面时抛出空指针异常

What is the expected output? What do you see instead?
输出的错误是：
java.lang.NullPointerException  
 at org.springside.modules.orm.hibernate.HibernateDao.countCriteriaResult(HibernateDao.java:251) 
 at org.springside.modules.orm.hibernate.HibernateDao.findPage(HibernateDao.java:144) 
 at org.springside.modules.orm.hibernate.HibernateDao.findPage(HibernateDao.java:296)

What version of the product are you using? On what operating system?
我用的是3.3.1版本

Please provide any additional information below.
我查看了这个类的这条语句是：
int totalCount = (Integer) 
c.setProjection(Projections.rowCount()).uniqueResult();

改为：

  // 执行Count查询
  Integer count = (Integer) c.setProjection(Projections.rowCount()).uniqueResult();
  int totalCount = count == null ? 0 : count;

后，异常消失
```

Original issue reported on code.google.com by `linq...@gmail.com` on 17 Jun 2010 at 11:05

**Comment by GoogleCodeExporter** [comment]
```
谢谢意见，已在3.3.4中修复
```

Original comment by `calvinxiu@gmail.com` on 8 Sep 2010 at 5:43
- Changed state: **Fixed**
