### ISSUE TITLE
关连查询时报错：could not resolve property  ******* 严重******@#（&@（&@￥（（

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zhangwenling/springside#33]
```
说明，有一个TacticsDate实体和一个Tactics实体，Tactics和TacticsDat
e是一对多的关系，结构如下：
Tactics：
        private String fieldType;
    private Boolean isModify = false;
    private String remark;
    private String tacticsName;
    private Long venueId;
    private List<TacticsDate> tacticsDates;

====================================
TacticsDate：
        private Date fromDate;
    private Date toDate;
    private Long venueId;
    private Tactics tactics;

我现在要通过TacticsDate关联查询，代码如下：
List<PropertyFilter> filters = new ArrayList<PropertyFilter>();
filters.add(new PropertyFilter("EQS_tactics.remark", "abc"));
List<TacticsDate> find = dateDao.find(filters);
System.out.println(find.size());

************** 文件在附件 ****************

查询报错如下：

org.hibernate.QueryException: could not resolve property: tactics.remark of: 
com.runchain.exercise.admin.entity.tactics.TacticsDate
    at org.hibernate.persister.entity.AbstractPropertyMapping.propertyException(AbstractPropertyMapping.java:67)
    at org.hibernate.persister.entity.AbstractPropertyMapping.toColumns(AbstractPropertyMapping.java:82)
    at org.hibernate.persister.entity.BasicEntityPropertyMapping.toColumns(BasicEntityPropertyMapping.java:54)
    at org.hibernate.persister.entity.AbstractEntityPersister.toColumns(AbstractEntityPersister.java:1367)
    at org.hibernate.loader.criteria.CriteriaQueryTranslator.getColumns(CriteriaQueryTranslator.java:457)
    at org.hibernate.loader.criteria.CriteriaQueryTranslator.getColumnsUsingProjection(CriteriaQueryTranslator.java:417)
    at org.hibernate.criterion.SimpleExpression.toSqlString(SimpleExpression.java:68)
    at org.hibernate.loader.criteria.CriteriaQueryTranslator.getWhereCondition(CriteriaQueryTranslator.java:357)
    at org.hibernate.loader.criteria.CriteriaJoinWalker.<init>(CriteriaJoinWalker.java:113)
    at org.hibernate.loader.criteria.CriteriaJoinWalker.<init>(CriteriaJoinWalker.java:82)
    at org.hibernate.loader.criteria.CriteriaLoader.<init>(CriteriaLoader.java:91)
    at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1578)
    at org.hibernate.impl.CriteriaImpl.list(CriteriaImpl.java:306)
    at org.springside.modules.orm.hibernate.SimpleHibernateDao.find(SimpleHibernateDao.java:272)
    at org.springside.modules.orm.hibernate.HibernateDao.find(HibernateDao.java:288)
    at com.runchain.exercise.admin.unit.dao.activity.AllFieldActivityDaoTest.testDate(AllFieldActivityDaoTest.java:41)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:585)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
    at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:82)
    at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:240)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
    at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:180)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

```

Original issue reported on code.google.com by `yanhonglei` on 29 Jul 2010 at 8:00

Attachments:
- [Tactics.java](https://storage.googleapis.com/google-code-attachments/springside/issue-33/comment-0/Tactics.java)
- [TacticsDate.java](https://storage.googleapis.com/google-code-attachments/springside/issue-33/comment-0/TacticsDate.java)
- [TacticsPrice.java](https://storage.googleapis.com/google-code-attachments/springside/issue-33/comment-0/TacticsPrice.java)
- [TacticsDateDaoTest.java](https://storage.googleapis.com/google-code-attachments/springside/issue-33/comment-0/TacticsDateDaoTest.java)

**Comment by GoogleCodeExporter** [comment]
```
这个问题，我也遇到了。也联系不到白衣天使，白衣天使现��
�应该也忙吧。不知道白衣天使会不会回复这个bug，希望能看�
��回复！
```

Original comment by `ycyang...@163.com` on 24 Dec 2010 at 8:07

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
我在3.3.4版本基础上添加了级联查询的功能，并且添加了对jqG
rid的支持(部分功能)
关联查询可以看看我改的代码：http://code.google.com/p/wsria/source/
browse/trunk/springside-3.3.4.x/src/main/java/org/springside/modules/orm/hiberna
te/HibernateDao.java?r=70

大家可以和原版的代码对比

添加了对jqGrid的功能可以访问：http://demo.wsria.com:10000/wsria-demo
```

Original comment by `yanhonglei` on 25 Dec 2010 at 3:39

**Comment by GoogleCodeExporter** [comment]
```
暂无修正计划
```

Original comment by `calvinxiu@gmail.com` on 5 May 2011 at 3:42
- Changed state: **WontFix**
